name: Build and Deploy Next.js to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repo
      - uses: actions/checkout@v3

      # 2. Set up Node.js 18.x
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build the Next.js app
      - name: Build
        run: npm run build

      # 5. (Optional) Prune dev dependencies to speed deploy
      - name: Prune devDependencies
        run: npm prune --production

      # 6. Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          # Replace with your actual Azure Web App name
          app-name: cliemetz-monitor  
          # This secret is automatically set up when you configure Deployment Center
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          # Deploy the entire project folder (with .next/, node_modules/, etc.)
          package: .
