name: Build and Deploy Next.js to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout your code
      - uses: actions/checkout@v3

      # 2. Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build the Next.js app
      - name: Build
        run: npm run build

      # 5. Prune devDependencies (optional)
      - name: Prune devDependencies
        run: npm prune --production

      # 6. Deploy to Azure Web App using your publish profile
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: cliemetz-monitor          # <-- make sure this matches exactly
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
